[package]
name = "lib_pyo3"
version = "0.1.0"
authors = ["Ni3nayka <egor_bakay@inbox.ru>"]
#edition = "2021"

[lib]
name = "lib_pyo3"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
